In [2]:
import os
os.environ['PATH'] += ':/opt/local/bin'
import torch

In [3]:
torch.manual_seed(42)
nums = torch.randint(low=0, high=10, size=(100,))
outs = torch.zeros(len(nums))
for i, j in enumerate(nums[:-1]):
    outs[i] = nums[i].item() + nums[i+1].item()


In [4]:
x = nums[:10]
y = outs[:10]
for i in range(len(x) - 1):
    print(i)
    context1 = x[i]
    context2 = x[i+1]
    answer = y[i]
    print(f"when context is {context1} + {context2} it equals {answer}")

0
when context is 2 + 7 it equals 9.0
1
when context is 7 + 6 it equals 13.0
2
when context is 6 + 4 it equals 10.0
3
when context is 4 + 6 it equals 10.0
4
when context is 6 + 5 it equals 11.0
5
when context is 5 + 0 it equals 5.0
6
when context is 0 + 4 it equals 4.0
7
when context is 4 + 0 it equals 4.0
8
when context is 0 + 3 it equals 3.0


In [5]:
block_size = 2
batch_size = 4


def get_batch():
    torch.manual_seed(42)
    ix = torch.randint(len(nums) - block_size, (batch_size,),)
    Xb = nums[ix]
    Yb = outs[ix]
#     x = torch.stack([nums[i:i+block_size] for i in ix])
#     y = torch.stack([nums[i+1:i+block_size+1] for i in ix])
    
    print(Xb)
    print(Yb)
    return Xb, Yb
    

get_batch()

tensor([8, 1, 6, 0])
tensor([9., 4., 6., 4.])


(tensor([8, 1, 6, 0]), tensor([9., 4., 6., 4.]))

In [16]:
X, Y = [], []
for i in range(len(nums[:10]) - 1):
    context = []
    context.append(nums[i])
    context.append(nums[i+1])
    X.append(context)
    Y.append(outs[i])

    

X = torch.tensor(X)
Y = torch.tensor(Y)

print(X.shape)
print("------")
print(Y.shape)




torch.Size([9, 2])
------
torch.Size([9])


In [ ]:
C = torch.randn((100,2))