In [21]:
import os
os.environ['PATH'] += ':/opt/local/bin'
import torch

In [54]:
torch.manual_seed(42)
nums = torch.randint(low=0, high=10, size=(100,))
outs = torch.zeros(len(nums))
for i, j in enumerate(nums[:-1]):
    outs[i] = nums[i].item() + nums[i+1].item()


In [45]:
block_size = 2
x = nums[:10]
y = outs[:10]
for i in range(len(x) - 1):
    print(i)
    context1 = x[i]
    context2 = x[i+1]
    answer = y[i]
    print(f"when context is {context1} + {context2} it equals {answer}")

0
when context is 2 + 7 it equals 9.0
1
when context is 7 + 6 it equals 13.0
2
when context is 6 + 4 it equals 10.0
3
when context is 4 + 6 it equals 10.0
4
when context is 6 + 5 it equals 11.0
5
when context is 5 + 0 it equals 5.0
6
when context is 0 + 4 it equals 4.0
7
when context is 4 + 0 it equals 4.0
8
when context is 0 + 3 it equals 3.0


In [64]:
def get_batch():
    torch.manual_seed(42)
    ix = torch.randint(len(nums) - 1, (4,),)
    print(ix)
    X = nums[ix]
    Y = outs[ix]
    print(Y)
    return X, Y
    

get_batch()

tensor([ 6, 95, 97, 58])
tensor([ 4.,  6., 10., 16.])


(tensor([0, 5, 9, 8]), tensor([ 4.,  6., 10., 16.]))